# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a07aa3108c4e8fa41c7c03805b0b5f8f3abb644198a1a9ef232bee0054f16b44c2881614e693a811c9654698caab982b927a3b945c8faaf572fed25d4122d50

test:
  secret_key_base: 6b65e4aa11628aeb1e4212791cde6b45ca9b332d66661eac5034e49b4b1d8c3415c4f64396cb2018cfaccc5231579fcbbdbacacc5f65fb647c82138805332cf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
